// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_multidns is a generated GoMock package.
package mock_multidns

import (
	reflect "reflect"
	time "time"

	multidns "github.com/d3mondev/multidns"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockClient) Resolve(domains []string, rrtype multidns.RRtype) []multidns.Record {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", domains, rrtype)
	ret0, _ := ret[0].([]multidns.Record)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockClientMockRecorder) Resolve(domains, rrtype interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockClient)(nil).Resolve), domains, rrtype)
}

// Mockresolver is a mock of resolver interface.
type Mockresolver struct {
	ctrl     *gomock.Controller
	recorder *MockresolverMockRecorder
}

// MockresolverMockRecorder is the mock recorder for Mockresolver.
type MockresolverMockRecorder struct {
	mock *Mockresolver
}

// NewMockresolver creates a new mock instance.
func NewMockresolver(ctrl *gomock.Controller) *Mockresolver {
	mock := &Mockresolver{ctrl: ctrl}
	mock.recorder = &MockresolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockresolver) EXPECT() *MockresolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *Mockresolver) Resolve(query string, rrtype multidns.RRtype) []multidns.Record {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", query, rrtype)
	ret0, _ := ret[0].([]multidns.Record)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockresolverMockRecorder) Resolve(query, rrtype interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*Mockresolver)(nil).Resolve), query, rrtype)
}

// Mocksleeper is a mock of sleeper interface.
type Mocksleeper struct {
	ctrl     *gomock.Controller
	recorder *MocksleeperMockRecorder
}

// MocksleeperMockRecorder is the mock recorder for Mocksleeper.
type MocksleeperMockRecorder struct {
	mock *Mocksleeper
}

// NewMocksleeper creates a new mock instance.
func NewMocksleeper(ctrl *gomock.Controller) *Mocksleeper {
	mock := &Mocksleeper{ctrl: ctrl}
	mock.recorder = &MocksleeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksleeper) EXPECT() *MocksleeperMockRecorder {
	return m.recorder
}

// Sleep mocks base method.
func (m *Mocksleeper) Sleep(t time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Sleep", t)
}

// Sleep indicates an expected call of Sleep.
func (mr *MocksleeperMockRecorder) Sleep(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sleep", reflect.TypeOf((*Mocksleeper)(nil).Sleep), t)
}
