// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_multidns is a generated GoMock package.
package mock_multidns

import (
	reflect "reflect"

	multidns "github.com/d3mondev/multidns"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockClient) Resolve(domains []string, rrtype multidns.RRtype) []multidns.Record {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", domains, rrtype)
	ret0, _ := ret[0].([]multidns.Record)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockClientMockRecorder) Resolve(domains, rrtype interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockClient)(nil).Resolve), domains, rrtype)
}

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockResolver) Resolve(query string, rrtype multidns.RRtype) []multidns.Record {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", query, rrtype)
	ret0, _ := ret[0].([]multidns.Record)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockResolverMockRecorder) Resolve(query, rrtype interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockResolver)(nil).Resolve), query, rrtype)
}
